
#alias ls='ls --color=auto'
alias ll='ls -alFh'
alias la='ls -A'
alias l='ls -CF'
alias ..="cd ../"
alias ...="cd ../../"
alias ....="cd ../../../"
alias sk='ssh luonan@10.8.160.227'
alias ssh227='ssh luonan@10.8.160.227'
alias sshAli='ssh root@47.92.222.162'
alias sshdev='ssh luonan@10.226.201.105'
alias sshxbdev='ssh zhaoxuebin@10.8.122.14'
alias sshxbmddev='ssh zhaoxuebin@10.110.232.242'
alias sshmd='ssh luonan@10.110.232.242'
alias dev='ssh luonan@10.8.118.129'
alias sshqa='ssh chaixihan@10.8.125.140'
alias gst='git status'
alias gl='git log'
alias grepflict='grep -lr "<<<<<<" .'
alias grep='grep --color=auto'
alias sc='screen'
alias god="sh dev_build.sh ; sh ./output/dev_bootstrap.sh"
alias fisdev='fisb release -w -d  dev'
alias dc='docker-compose'
alias fisclr='fisb release -c'
alias fisdevo='fisb release -cDoumpd luonan_local'
alias ifcfg='ifconfig | grep netmask'
alias inspector='node-inspector -p=8089'
alias ndebug='node --debug=5859 ./bin/www'
alias kpt='/Users/raku/Sites/shell_playground/killByPort.sh'
alias make_commit='/Users/raku/Sites/shell_playground/commit.sh'
alias make_update='/Users/raku/Sites/shell_playground/resetproject.sh'
alias kdv='~/Sites/shell_playground/killDlv.sh'
alias toDocker='docker exec -it'
alias gti='git'
alias gut='git'
alias cp='cp -r'
alias j='z'
alias redis79='redis-cli -h 10.3.40.43 -p 3708'
alias redisOL='redis-cli -h 10.6.17.66 -p 6651'
